[package]
name = "rb_parsers"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/rb_tokenizer",
    "crates/rb_parser",
    "crates/visitor",
]

[dependencies]

[dev-dependencies]
rb_tokenizer = { path = "crates/rb_tokenizer" }
rb_parser = { path = "crates/rb_parser" }